export const GTE_BANNER_LIST = 'home/banner/GTE_BANNER_LIST'
export const MAKE_WX_SHOW = 'home/banner/MAKE_WX_SHOW'
export const MAKE_WX_HIDE = 'home/banner/MAKE_WX_HIDE'
export const MAKE_WX_OUT = 'home/banner/MAKE_WX_OUT'
export const GET_SHOW_ACTION = 'home/banner/GET_SHOW_ACTION'
export const GET_LINE_ACTION = 'home/banner/GET_LINE_ACTION'
export const GET_COMMENT = 'home/banner/GET_COMMENT'
